# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'geoLocation' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for geoLocation
  pod 'Firebase'
  pod 'Firebase/Core', :modular_headers => true
  pod 'Firebase/Messaging', :modular_headers => true 

end
